import { ClerkProvider } from "@clerk/nextjs/app-beta";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          style={{
            margin: 0,
          }}
        >
          {" "}
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
