name: CI
 
on:
  push:
    branches: ["main"]
 
jobs:
  fly:
      name: Build and Deploy fly
      timeout-minutes: 15
      runs-on: ubuntu-latest
      steps: 
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --dockerfile apps/token/Dockerfile --config apps/token/fly.toml --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  api:
      name: Build and Deploy api
      timeout-minutes: 15
      runs-on: ubuntu-latest
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      # env:
      #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
 
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.32.2
 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'
 
        - name: Install dependencies
          run: pnpm install

        - name: wrangler
          run: pnpm add -g wrangler

        - name: wrangler
          run: pnpm add -g turbo
 
        - name: Build
          run: turbo build --filter=...webhooks
 
        - name: Deploy github actions
          run: cd apps/api && CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} wrangler publish
  hooks:
      name: Build and Deploy hooks 
      timeout-minutes: 15
      runs-on: ubuntu-latest
      # To use Remote Caching, uncomment the next lines and follow the steps below.
      # env:
      #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
 
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.32.2
 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'
 
        - name: Install dependencies
          run: pnpm install

        - name: wrangler
          run: pnpm add -g wrangler
        
        - name: wrangler
          run: pnpm add -g turbo
 
        - name: Build
          run: turbo build --filter=...webhooks
        
        - name: Deploy github actions
          run: cd apps/hooks && CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} wrangler publish